Repository gumbo-millennium/website, pull requests merged in 2020-10, with the labels that each got.

#125 Display an error message when guests visit member only activities
  app/Http/Controllers/Activities/DisplayController.php
  resources/lang/nl/activities.php
  resources/views/errors/403.blade.php
Labels: enhancement, hacktoberfest

#128 Changed Nova install system to allow for deployments
  .github/CODEOWNERS
  Envoy.blade.php
  composer.lock
  library/composer/nova/composer.json
  library/composer/nova/src/Events/ServingNova.php
  library/composer/nova/src/Nova.php
  library/composer/nova/src/NovaCoreServiceProvider.php
Labels: bug, hacktoberfest-accepted

#129 Fixed Laravel Nova not loading properly when it's available
  app/Providers/AppServiceProvider.php
  config/services.php
  phpcs.xml
Labels: bug, hacktoberfest-accepted

#131 Fixed sticky activities
  app/Models/Activity.php
Labels: bug, hacktoberfest, hacktoberfest-accepted
